[package]
name = "service"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
uuid.workspace = true

domain.path = "../domain"
