[package]
name = "domain"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
uuid.workspace = true

[lints.clippy]
pedantic = "warn"
